window.onload= function() {
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("3").textContent = "\u2022"
    document.getElementById("5").textContent = "\u2022"
    document.getElementById("7").textContent = "\u2022"
    document.getElementById("10").textContent = "\u2022"
    document.getElementById("12").textContent = "\u2022"
    document.getElementById("14").textContent = "\u2022"
    document.getElementById("16").textContent = "\u2022"
    document.getElementById("17").textContent = "\u2022"
    document.getElementById("19").textContent = "\u2022"
    document.getElementById("21").textContent = "\u2022"
    document.getElementById("23").textContent = "\u2022"

    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"
    document.getElementById("1").textContent = "\u2022"

}
